spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 2e7cf0ab5c30d398d9f6
            client-secret: ${CLIENT_SECRET}
            scope: name,email,avatar-url