# server config
server:
  port: 8080
  servlet:
    session:
      timeout: 360000s
    # 인코딩 UTF-8로 설정
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  profiles:
    # 운영환경 or 로컬 환경 중에 선택하세요.
    active: dev
    web:
      resources:
        static-locations: file:src/main/resources/static/
mybatis:
  mapper-locations: mappers/**/*.xml

